services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi_container
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres_container:5432/postgres
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
